# Configuration for the Blunderbuss GitHub app. For more info see
# https://github.com/googleapis/repo-automation-bots/tree/main/packages/blunderbuss

assign_issues_by:
- labels:
  - 'api: cloudiot'
  to:
  - joeklemm
- labels:
  - 'api: bigtable'
  - 'api: datastore'
  - 'api: firestore'
  to:
  - GoogleCloudPlatform/cloud-native-db-dpes
- labels:
  - 'api: cloudsql'
  to:
  - GoogleCloudPlatform/infra-db-sdk
- labels:
  - 'api: spanner'
  to:
  - dazuma

assign_prs_by:
- labels:
  - 'api: cloudiot'
  to:
  - joeklemm
- labels:
  - 'api: bigtable'
  - 'api: datastore'
  - 'api: firestore'
  to:
  - GoogleCloudPlatform/cloud-native-db-dpes
- labels:
  - 'api: cloudsql'
  to:
  - GoogleCloudPlatform/infra-db-sdk

assign_issues:
  - 'dazuma'
