# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require "rake/testtask"
require "bundler"

Rake::TestTask.new "test" do |t|
  t.libs << "test"
  t.test_files = FileList["test/**/*_test.rb"]
  t.warning = true
end

task "bundle" do
  Dir.chdir __dir__
  bundle_update_in_cwd
end

def bundle_update_in_cwd
  if File.file? "Gemfile"
    puts "Updating bundle in #{Dir.pwd}"
    Bundler.with_clean_env do
      system "bundle update"
    end
  end
  Dir.foreach "." do |entry|
    next unless File.directory? entry
    next if entry =~ /^\.\.?$/
    Dir.chdir entry do
      bundle_update_in_cwd
    end
  end
end
