inherit_gem:
  google-style: google-style.yml
AllCops:
  Exclude:
    - "**/acceptance/**"
    - "**/spec/**"
    - "**/skip_spec/**"
    - "Rakefile"
Layout/LineLength:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Exclude:
    - "iot/iot.rb"
Lint/DuplicateRequire:
  Exclude:
    - "stackdriver/*.*"
Lint/NonLocalExitFromIterator:
  Exclude:
    - "functions/**/*.rb"
Lint/RescueException:
  Exclude:
    - "appengine/sendgrid/app.rb"
Lint/SuppressedException:
  Exclude:
    - "run/rails-cat_album/bin/spring"
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/BlockComments:
  Exclude:
    - "**/routes.rb"
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/GlobalVars:
  Exclude:
    - "kms/kms.rb"
    - "iot/iot.rb"
    - "functions/slack/app.rb"
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/LineEndConcatenation:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  AllowParenthesesInChaining: true
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses_except_multiline
Style/MixinUsage:
  Exclude:
    - "appengine/**/rails*/**/*"
Style/Next:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Style/WordArray:
  EnforcedStyle: brackets

