# [START gae_flex_websocket_dependencies]
source "https://rubygems.org"

gem "sinatra"
gem "faye-websocket"

gem "thin"
# [END gae_flex_websocket_dependencies]

group :test do
  gem "rack-test"
  gem "rspec"
  gem "capybara"
  gem "capybara-webkit"
end
