# Copyright 2020 Google, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# [START cloud_sql_sqlserver_activerecord_connect_tcp]
tcp: &tcp
  adapter: sqlserver
  # Configure additional properties here.
# [END cloud_sql_sqlserver_activerecord_connect_tcp]
  # [START cloud_sql_sqlserver_activerecord_limit]
  # 'pool' is the maximum number of permanent connections to keep.
  pool: 5
  # [END cloud_sql_sqlserver_activerecord_limit]
  # [START cloud_sql_sqlserver_activerecord_timeout]
  # 'timeout' is the maximum number of seconds to wait when retrieving a
  # new connection from the pool. After the specified amount of time, an
  # ActiveRecord::ConnectionTimeoutError will be raised.
  timeout: 5000
  # [END cloud_sql_sqlserver_activerecord_timeout]

  # [START cloud_sql_sqlserver_activerecord_backoff]
  # ActiveRecord automatically uses delays between failed connection attempts,
  # but provides no arguments for configuration.
  # [END cloud_sql_sqlserver_activerecord_backoff]
  
  # [START cloud_sql_sqlserver_activerecord_connect_tcp]
  # Note: Saving credentials in environment variables is convenient, but not
  # secure - consider a more secure solution such as
  # Cloud Secret Manager (https://cloud.google.com/secret-manager) to help
  # keep secrets safe.
  username: <%= ENV["DB_USER"] %>  # e.g. "my-database-user"
  password: <%= ENV["DB_PASS"] %> # e.g. "my-database-password"
  database: <%= ENV.fetch("DB_NAME") { "vote_development" } %>
  host: <%= ENV.fetch("INSTANCE_HOST") { "127.0.0.1" }%> # '172.17.0.1' if deployed to GAE Flex
  port: <%= ENV.fetch("DB_PORT") { 1433 }%> 
  # [END cloud_sql_sqlserver_activerecord_connect_tcp]

development:
  <<: *tcp

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *tcp
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("DB_NAME") { "vote_test" } %>

production:
  <<: *tcp
  database: <%= ENV.fetch("DB_NAME") { "vote_production" } %>
