source "https://rubygems.org"

gem "sinatra", "~>2.0"
gem "puma"

group :test do
  gem "rack-test"
  gem "rest-client"
  gem "rspec"
  gem "rspec_junit_formatter"
  gem "rspec-retry"
  gem "rubysl-securerandom"
end
