# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# DO NOT EDIT! This is a generated sample ("Request",  "job_search_create_client_event")

# sample-metadata
#   title:
#   description: Creates a client event
#   bundle exec ruby samples/v4beta1/job_search_create_client_event.rb [--project_id "Your Google Cloud Project ID"] [--tenant_id "Your Tenant ID (using tenancy is optional)"] [--request_id "[request_id from ResponseMetadata]"] [--event_id "[Set this to a unique identifier]"]

require "google/cloud/talent"

# [START job_search_create_client_event]

# Creates a client event
#
# @param project_id {String} Your Google Cloud Project ID
# @param tenant_id {String} Identifier of the Tenant
# @param request_id {String} A unique ID generated in the API responses.
# Value should be set to the request_id from an API response.
# @param event_id {String} A unique identifier, generated by the client application
def sample_create_client_event project_id, tenant_id, request_id, event_id
  # Instantiate a client
  event_client = Google::Cloud::Talent::Event.new version: :v4beta1

  # project_id = "Your Google Cloud Project ID"
  # tenant_id = "Your Tenant ID (using tenancy is optional)"
  # request_id = "[request_id from ResponseMetadata]"
  # event_id = "[Set this to a unique identifier]"
  formatted_parent = event_client.class.tenant_path(project_id, tenant_id)

  # The timestamp of the event as seconds of UTC time since Unix epoch
  # For more information on how to create google.protobuf.Timestamps
  # See: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/timestamp.proto
  seconds = 0
  create_time = { seconds: seconds }

  # The type of event attributed to the behavior of the end user
  type = :VIEW

  # List of job names associated with this event
  jobs_element = "projects/[Project ID]/tenants/[Tenant ID]/jobs/[Job ID]"
  jobs_element_2 = "projects/[Project ID]/tenants/[Tenant ID]/jobs/[Job ID]"
  jobs = [jobs_element, jobs_element_2]
  job_event = { type: type, jobs: jobs }
  client_event = {
    request_id: request_id,
    event_id: event_id,
    create_time: create_time,
    job_event: job_event
  }

  response = event_client.create_client_event(formatted_parent, client_event)
  puts "Created client event"
end
# [END job_search_create_client_event]


require "optparse"

if $PROGRAM_NAME == __FILE__

  project_id = "Your Google Cloud Project ID"
  tenant_id = "Your Tenant ID (using tenancy is optional)"
  request_id = "[request_id from ResponseMetadata]"
  event_id = "[Set this to a unique identifier]"

  ARGV.options do |opts|
    opts.on("--project_id=val") { |val| project_id = val }
    opts.on("--tenant_id=val") { |val| tenant_id = val }
    opts.on("--request_id=val") { |val| request_id = val }
    opts.on("--event_id=val") { |val| event_id = val }
    opts.parse!
  end


  sample_create_client_event(project_id, tenant_id, request_id, event_id)
end
