# [START gae_flex_websocket_dependencies]
source "https://rubygems.org"

gem "faye-websocket"
gem "sinatra"

gem "thin"
# [END gae_flex_websocket_dependencies]

group :test do
  gem "capybara"
  gem "cuprite"
  gem "rack-test"
  gem "rspec"
  gem "rspec_junit_formatter"
end
