# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# [START getting_started_requirements]
gem "jwt", "~> 2.2"
gem "sinatra", "~> 2.0"
# [END getting_started_requirements]
