inherit_gem:
    google-style: google-style.yml

Metrics/BlockLength:
    Exclude:
        - "acceptance/*.rb"
Style/IfUnlessModifier:
  Exclude:
    - "snippets.rb"
Style/RegexpLiteral:
    Enabled: false
