runtime: ruby
vm: true
entrypoint: bundle exec ruby app.rb -p $PORT

beta_settings:
  # Enable Google Cloud Endpoints API management.
  use_endpoints_api_management: true
  # Specify the Swagger API specification.
  endpoints_swagger_spec_file: swagger.yaml
