source "https://rubygems.org"

gem "sinatra"
gem "json"
gem "rack-cors"

# Dependencies for ./clients/
group :development do
  gem "rest-client"
  gem "signet"
end

# Dependencies for ./spec/
group :test do
  gem "rspec"
  gem "rack-test"
end
