# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "google-cloud-bigtable", "~> 1.0", ">= 1.0.2"

group :test do
  gem "rspec"
end
