# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "google-cloud-bigtable", "~> 0.3.0"

group :test do
  gem "rspec"
end
